### ISSUE TITLE
import pyDeform failed

### ISSUE THREAD

**Issue by jellyDL** [hjwdzh/MeshODE#6]
when I “import pyDeform”，an error occurs：
pyDefrom.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __ZN3c105ErrorC1ENS_14SourceLocationERKNSt7_ ...

**Environment:**
ubuntu16.04(gcc:5.4.0)
python:3.6.10
pytorch:1.4.0

Cloud you give more information about the environment？

**Comment by hjwdzh** [comment]
First, please check whether this file is successfully built in the build folder. Second, please make sure you set the python path using: export PYTHONPATH=$PYTHONPATH:$(pwd)
