### ISSUE TITLE
prediction and generalization of the network 

### ISSUE THREAD

**Issue by jellyDL** [hjwdzh/MeshODE#7]
Many thanks for your great paper！
The network needs input pairs of source and target，is that possible that only given a source obj，output a prediction obj after training（without target obj）？And the network is relatively lightweight，will it has a good effect for some real data？

**Comment by hjwdzh** [comment]
The idea is to deform one to the other. If there is only one source obj, not sure what you expect as prediction.

It should work for real data the same as for CAD model. However, it has similar limitations with ICP -- it requires objects to be roughly aligned (e.g. a unique canonical space), or the optimization could not converge to a ideal state.

**Comment by zhouhao957** [comment]
Hello, May I ask your ceres-Solver, Cgal, Eigen, Libigl, Pybind11 version?

i am run：make-j8。Can you give me some advice if the following questions arise

[ 3%] Building CXX object CMakeFiles/deform_optim.dir/src/lib/linear.cc.o
:0:25: error: token "�" is not valid in preprocessor expressions
:0:25: error: token "�" is not valid in preprocessor expressions
